### ISSUE TITLE
Skipped tests are marked as with the passed status in the testplan

### ISSUE THREAD

**Issue by AnnEnervalis** [bryanbcook/azdevops-testplan-extension#31] opened 2024-07-04 07:03 UTC
**Description**

I have a number of skipped tests that don't run yet.
You can see in the tests tab that they are effectivaly not run:
![image](https://github.com/bryanbcook/azdevops-testplan-extension/assets/144136922/bbc17f29-bb83-4dc1-b1c6-ca5024da8b29)

However, in the testplan the tests are marked as passed:
![image](https://github.com/bryanbcook/azdevops-testplan-extension/assets/144136922/d3af334a-2bd8-4e0a-8ab5-c94b2d1b084e)

Can you mark them as 'NotExecuted' please?

**Environment Details**

_provide details about your pipeline environment_

- build-agent: self-hosted 
- test-format: webdriverIO with mocha
- test-lanugage: Typescript
- pipeline-format: yaml 

If you need more information, don't hesitate to ask.
(Thanks for this plugin, it really helps)

**Comment by bryanbcook** [comment] 2024-07-04 12:30
Thanks for raising this.

To help clarify if this is an issue converting your mocha test results into a common format, or a mismatch when publishing to the Test Plan:

- Can you provide a sample of your test results?
- Were these tests previously executed and marked as Passed and the status is not being reset?

**Comment by AnnEnervalis** [comment] 2024-07-04 14:00
These are new tests or tests that were marked previously as passed.  Both have the same behavior.
I can see that every run adds a 'Passed' status, so I don't think the previous state is related.

In attachment you can find the junit file.  Does that help?
[junit-results-file.zip](https://github.com/user-attachments/files/16099792/junit-results-file.zip)

**Comment by bryanbcook** [comment] 2024-07-04 21:36
Ok. I think the issue might be a bug in the test-parser library that I'm using to convert test-formats into a common format. Your skipped tests in the JUnit xml results appear as:

```xml
<testcase ....>
   <skipped/>
</testcase>
```

I think the test-parser library is expecting an attribute instead of an element. I'll do some research to determine if this is a variant of the JUnit format (there are lots of variants) and log a bug for this.

**Comment by bryanbcook** [comment] 2024-07-04 21:51
Logged https://github.com/test-results-reporter/parser/issues/70

**Comment by bryanbcook** [comment] 2024-07-10 15:42
@AnnEnervalis just an update - the above defect has been fixed, now we're just waiting on a new release of the package.

**Comment by bryanbcook** [comment] 2024-07-18 19:25
@AnnEnervalis new version published. I'll leave this open and hope to hear from you soon.

**Comment by AnnEnervalis** [comment] 2024-07-23 09:05
Hi, 
I am afraid that it doesn't work any better.  I notice that failed tests also are reported as passed.  Skipped tests are also still 'passed'
In attachement you can find a new junit file.  If you look for testcase 146035, you see that it failed, but It marks as 'passed'
![image](https://github.com/user-attachments/assets/1c8a4a17-8a6a-4218-9922-d24d96ebc75c)

[junit-results-file (2).zip](https://github.com/user-attachments/files/16346261/junit-results-file.2.zip)

**Comment by bryanbcook** [comment] 2024-07-23 16:24
That's frustrating! Let me see if I can repurpose your test results to one of my Test Plans and see if I can reproduce the issue. There was a bug in the test-parser library for Skipped tests, hopefully there isn't one for errors too. [But looking at my code](https://github.com/bryanbcook/azdevops-testplan-extension/blob/f1bd916b7baa6ce47af116fd32e81d9695437519/PublishTestPlanResultsV1/publishing/TestRunPublisher.ts#L61C11-L61C110), the error could be on my end too.

I notice in your test results that 146035 appears more than once, so that might also be contributing to some of the confusion. One of the results is Skipped, another is Error.

**Comment by bryanbcook** [comment] 2024-07-23 16:46
can you provide the YAML you're using for my extension?

**Comment by AnnEnervalis** [comment] 2024-07-24 05:36
`    - task: PublishTestPlanResults@0
      displayName: 'Publish HMI Tool Results to Test Plan'
      inputs:
       testResultFormat: 'jUnit'
       testResultFiles: 'junitResults/junit-results-file-hmi-testtool.xml'
      condition: eq(variables.TESTHMITOOL, 'true')`

**Comment by bryanbcook** [comment] 2024-07-24 17:41
I mention the duplicates because the matching strategy will match the first test result and discard the second. I can probably add some additional logging to reflect this.

Your test framework automatically retries tests and logs them in the result file more than once?

**Comment by bryanbcook** [comment] 2024-07-25 17:48
I'm having some challenges reproducing your issue.

I took your jUnit xml and reduced it to 5 test cases: [test-cleansed.zip](https://github.com/user-attachments/files/16381279/test-cleansed.zip):
* I modified the test numbers in your test names to match test case numbers from my test plan.
* I included duplicates to demonstrate how these are processed.
* I also reviewed the [code block mentioned above](https://github.com/bryanbcook/azdevops-testplan-extension/blob/f1bd916b7baa6ce47af116fd32e81d9695437519/PublishTestPlanResultsV1/publishing/TestRunPublisher.ts#L61C11-L61C110), and verified through Postman that the DevOps REST API will accept string or enum values, so the extension isn't sending an invalid value.

| Test Case | Test Name | Test Result | Test Case Result |
|-|-|-|-|
| 167 | 167 Verify the Summary page error elements when all of the previous modules was unsuccessful | Passed  | Passed |
| 174 | 174 Verify the Summary page success elements when all previous modules were successful (skipped)| `<skipped/>` | Not Executed |
| 174 | 174 Verify the Summary page success elements when all previous modules were successful (failed) | `<failure/>` | N/A - duplicate |
| 175 | 175 Verify the Summary page error elements when a random previous module was unsuccessful | `<skipped/>` | Not Executed |
| 176 | 176 Verify the Summary page error elements when a random previous module was unsuccessful | `<failure/>` | Failed |

I executed the extension locally and my test plan shows the results being reflected with the above. I also repeated my experiments by resetting the test cases to "Active" to ensure that they were be modified by the extension.

![](https://github.com/user-attachments/assets/73a54747-12e7-4d40-956d-08a2042622a1)

The progress report reflects the changes as well.

![image](https://github.com/user-attachments/assets/39c5532b-77fd-44bf-a89d-4b11e8755663)

I'll release a version shortly with some additional debug logging to help you troubleshoot, but I would like to confirm that the Skipped tests are being reported as Not Executed and that we're not trying to solve multiple issues simultaneously. To do this, can you run a test suite with only a single skipped test and publish that against the test plan to rule out issues with duplicates or other interfering symptoms?

**Comment by bryanbcook** [comment] 2024-08-15 15:24
@AnnEnervalis the initial defect of junit skipped tests was resolved and released in 0.1.14

Marking this as closed as I was not able to reproduce your issue after the fix.

If you continue to experience issues, please comment here or open a new defect.

**Closed by bryanbcook** 2024-08-15 15:24 UTC
Labels: bug
